version: '3.8'

services:
  redis-server:
    image: redis:7-alpine
    container_name: redis-cache-container
    ports:
      - "6379:6379"
    networks:
      - global-microservices-net

  postgres-order:
    image: postgres:15
    container_name: order-postgres-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - global-microservices-net

  ms-order-service:
    build: ./ms-order-service
    container_name: ms-order-service-app
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/order_db
      REDIS_HOST: redis-server
    depends_on:
      - postgres-order
      - courier-service
      - rabbitmq-server
      - redis-server
    networks:
      - global-microservices-net

networks:
  global-microservices-net:
    driver: bridge